CREATE DATABASE VETERINARIA
GO

USE VETERINARIA
GO

--DROP DATABASE VETERINARIA


BEGIN TRY 
BEGIN TRANSACTION
    CREATE TABLE CLIENTE(
        ID_CLIENTE INT IDENTITY (1,1) NOT NULL CONSTRAINT PK_CLIENTE PRIMARY KEY,
        NOMBRE VARCHAR(20) NOT NULL,
        APELLIDO1 VARCHAR(20) NOT NULL,
        APELLIDO2 VARCHAR(20) NOT NULL,
        FECHA_NACIMIENTO DATE NOT NULL,
        TELEFONO VARCHAR(20) NOT NULL,
        EMAIL VARCHAR(50),
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_C DEFAULT 0
    )

    CREATE TABLE VENDEDOR(
        ID_VENDEDOR INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_VENDEDOR PRIMARY KEY,
        NOMBRE VARCHAR(20) NOT NULL,
        APELLIDO1 VARCHAR(20) NOT NULL,
        APELLIDO2 VARCHAR(20) NOT NULL,
        FECHA_NACIMIENTO DATE NOT NULL,
        TELEFONO INT NOT NULL,
        EMAIL VARCHAR(50),
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_VEN DEFAULT 0
    )

    CREATE TABLE VETERINARIO(
        ID_VETERINARIO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_VETERINARIO PRIMARY KEY,
        NOMBRE VARCHAR(20) NOT NULL,
        APELLIDO1 VARCHAR(20) NOT NULL,
        APELLIDO2 VARCHAR(20) NOT NULL,
        FECHA_NACIMIENTO DATE NOT NULL,
        TELEFONO INT NOT NULL,
        EMAIL VARCHAR(50),
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_VET DEFAULT 0
    )

    CREATE TABLE FACTURA_COMPRA(
        ID_COMPRA INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_FACTURA_C PRIMARY KEY,
        FECHA DATETIME NOT NULL CONSTRAINT DF_FACTURA_FECHA_C DEFAULT GETDATE(),
        ID_VENDEDOR INT NOT NULL CONSTRAINT DF_FC_VENDEDOR DEFAULT 0,
        ID_PROVEEDOR INT NOT NULL CONSTRAINT DF_FC_PROVEEDOR DEFAULT 0,
        TIPO VARCHAR(10) NOT NULL CONSTRAINT CK_TIPO_FAC_C CHECK(TIPO IN ('CONTADO', 'CREDITO'))
            CONSTRAINT DF_TIPO_FAC_C  DEFAULT 'CONTADO',
        IMPORTE DECIMAL(10,2) NOT NULL,
        DESCUENTO DECIMAL(10,2) NOT NULL,
        ESTADO VARCHAR(10) NOT NULL CONSTRAINT CK_ESTADO_COM CHECK(ESTADO IN('PENDIENTE', 'CANCELADO'))
            CONSTRAINT DF_ESTADO_FAC_C DEFAULT 'PENDIENTE',
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_FC DEFAULT 0
    )

    CREATE TABLE FACTURA_VENTA(
        ID_VENTA INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_FACTURA_V PRIMARY KEY,
        FECHA DATETIME NOT NULL CONSTRAINT DF_FACTURA_FECHA_V DEFAULT GETDATE(),
        ID_VENDEDOR INT NOT NULL CONSTRAINT DF_FV_VENDEDOR DEFAULT 0,
        ID_CLIENTE INT NOT NULL CONSTRAINT DF_FV_CLIENTE DEFAULT 0,
        TIPO VARCHAR(10) NOT NULL CONSTRAINT CK_TIPO_FAC_V CHECK(TIPO IN ('CONTADO', 'CREDITO'))
            CONSTRAINT DF_TIPO_FAC_V  DEFAULT 'CONTADO',
        DESCUENTO DECIMAL(10,2) NOT NULL CONSTRAINT DF_DESCUENT_VENTA DEFAULT 0,
        IMPORTE DECIMAL(10,2) NOT NULL CONSTRAINT DF_IMPORTE DEFAULT 0,
        ESTADO VARCHAR(10) NOT NULL CONSTRAINT CK_ESTADO_VEN CHECK(ESTADO IN('PENDIENTE', 'CANCELADO'))
            CONSTRAINT DF_ESTADO_FAC_V DEFAULT 'PENDIENTE',
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_FV DEFAULT 0
    )

    CREATE TABLE DETALLE_SERVICIO(
        ID_VENTA INT NOT NULL,
        ID_SERVICIO INT NOT NULL,
        DESCRIPCION VARCHAR(100) NOT NULL,
        ID_VETERINARIO INT NOT NULL,
        ID_ANIMAL INT NOT NULL,
        CANTIDAD INT NOT NULL,
        PRECIO DECIMAL(10,2) NOT NULL,
        DESCUENTO DECIMAL(10,2) NOT NULL,
        TOTAL DECIMAL(10,2) NOT NULL,
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_DS DEFAULT 0,
        CONSTRAINT PK_DETAL_SERV PRIMARY KEY (ID_VENTA, ID_SERVICIO)
    )

    

    CREATE TABLE DETALLE_PRODUCTO(
        ID_VENTA INT NOT NULL,
        ID_PRODUCTO INT NOT NULL,
        DESCRIPCION VARCHAR(50) NOT NULL,
        CANTIDAD INT NOT NULL,
        PRECIO DECIMAL(10,2)NOT NULL,
        DESCUENTO DECIMAL(10,2)NOT NULL,
        TOTAL DECIMAL(10,2) NOT NULL,
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_DP DEFAULT 0
    )

    CREATE TABLE SERVICIO(
        ID_SERVICIO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SERVICIO PRIMARY KEY,
        DESCRIPCION VARCHAR(100) NOT NULL,
        PRECIO DECIMAL(10,2) NOT NULL,
        DESCUENTO DECIMAL(10,2) NOT NULL,
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_SER DEFAULT 0
    )

    CREATE TABLE PRODUCTO(
        ID_PRODUCTO INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PRODUCTO PRIMARY KEY,
        DESCRIPCION VARCHAR(100) NOT NULL,
        CATEGORIA VARCHAR(20) NOT NULL,
        PRECIO DECIMAL(10,2) NOT NULL,
        DESCUENTO DECIMAL(10,2) NOT NULL,
        EXISTENCIA INT NOT NULL,
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_PROD DEFAULT 0
    )

    CREATE TABLE PROVEEDOR(
        ID_PROVEEDOR INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PROVEEDOR PRIMARY KEY,
        NOMBRE_COMERCIAL VARCHAR(50) NOT NULL,
        DIRECCION VARCHAR(100) NOT NULL,
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_PROV DEFAULT 0
    )

    CREATE TABLE PRODUCTO_PROVEEDOR(
        ID_PRODUCTO INT NOT NULL CONSTRAINT PK_PRODUCTO_P PRIMARY KEY,
        ID_PROVEEDOR INT NOT NULL,
        DESCRIPCION VARCHAR(100) NOT NULL,
        CATEGORIA VARCHAR(10) NOT NULL,
        PRECIO DECIMAL(10,2) NOT NULL,
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_PROD_P DEFAULT 0
    )

    CREATE TABLE ANIMAL(
        ID_ANIMAL INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ANIMAL PRIMARY KEY,
        ID_CLIENTE INT NOT NULL,
        ALIAS VARCHAR(30) NOT NULL,
        ESPECIE VARCHAR(30) NOT NULL,
        RAZA VARCHAR(30) NOT NULL    ,
        COLOR VARCHAR(30) NOT NULL,
        FECHA_NACIMIENTO DATE NOT NULL CONSTRAINT DF_NACIMIENTO DEFAULT GETDATE(),
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_AN DEFAULT 0
    )

    CREATE TABLE HISTORIA(
        ID_HISTORIA INT IDENTITY(1,1) NOT NULL CONSTRAINT PkK_HISTORIA PRIMARY KEY,
        ID_ANIMAL INT NOT NULL,
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_HIS DEFAULT 0
    )

    CREATE TABLE DETALLE_HISTORIA(
        ID_HISTORIA INT NOT NULL,
        FECHA DATE NOT NULL CONSTRAINT DF_DET_FECHA DEFAULT GETDATE(),
        DESCRIPCION VARCHAR(100) NOT NULL,
        PESO DECIMAL(10,2) NOT NULL,
        BORRADO_E BIT NOT NULL CONSTRAINT DF_BORRADO_DET_HIS DEFAULT 0
    )
COMMIT TRANSACTION
END TRY
BEGIN CATCH
    PRINT 'HUBO ERROR';
    THROW
    ROLLBACK TRANSACTION
END CATCH

INSERT INTO CLIENTE(NOMBRE,APELLIDO1,APELLIDO2,FECHA_NACIMIENTO,TELEFONO,EMAIL)
VALUES
('STEVEN','SOZA','MALIANO','1994-06-18','72171608','SOZATEV@GMAIL.COM'),
('MARTIN','SOLANO','CUÑA','1997-03-18','28395493','CARLSA.COM'),
('JUAN','PEREZ','QUINCHO','1994-06-18','82348283','MATMAIL.COM'),
('PEDRO','SPROUL','WILLIAMS','1994-06-18','82348283','JUAN@GMAIL.COM'),
('ANDREW','ZELEDON','ARROYO','1994-06-18','28495034','FANDON@GMAIL.COM'),
('MAIKOL','PEREZ','QUINCHO','1994-06-18','82348283','MAIKOL@GMAIL.COM'),
('MARIA','SALAS','MIRANDA','1954-03-18','45346564','MAR@GMAIL.COM')

INSERT INTO VENDEDOR(NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, TELEFONO, EMAIL)
VALUES
('FRANCISO','LORIA','AGUILAR','1990-03-22','23859403','FRANSUPR@GMAIL.COM'),
('MARCO','MENDEZ','PEREZ','1990-03-22','23859403','MARME@GMAIL.COM'),
('JIMENA','GARCIA','LOPEZ','1990-03-22','23859403','JIMGARE@GMAIL.COM'),
('YANCI','VILLALTA','PEREZ','1990-03-22','23859403','VILLATA@GMAIL.COM'),
('MARCO','SUARÉZ','PEREZ','1990-03-22','23859403','FRANSUPR@GMAIL.COM')

INSERT INTO PRODUCTO(DESCRIPCION, CATEGORIA, PRECIO, DESCUENTO, EXISTENCIA)
VALUES
('Super can', 'Alimento', 2045.23, 0.0, 30),
('Collar', 'Articulo', 12356.23, 0.0,30),
('Vacuna', 'Medicamento', 4234.23, 0.0, 0),
('Acetonil', 'Medicamento', 2323.23, 0.0, 100),
('Ascan', 'Alimento', 2234.23, 0.0, 20)

INSERT INTO SERVICIO(DESCRIPCION, PRECIO, DESCUENTO)
VALUES
('Radiográfia',42320.23, 0),
('Observación',8220.23, 0),
('Corte de pelo',6220.23, 0),
('Consulta',20320.23, 0),
('Vacuna',3320.23, 0),
('Cuido',10320.23, 0)

INSERT INTO VETERINARIO(NOMBRE, APELLIDO1, APELLIDO2, FECHA_NACIMIENTO, TELEFONO, EMAIL)
VALUES 
('Federico', 'Lopéz', 'Moreira','1987-06-18','38573949','FEDE@GMAIL.COM'),
('Mariam', 'Salas', 'Bonilla','1987-06-18','365763234', 'asd@GMAIL.COM'),
('Felipe', 'Garcia', 'Nuñez','1987-06-18','365763234', 'A34fdsa@GMAIL.COM'),
('Malcom', 'Vargas', 'Marin','1987-06-18','365763234', '45sfgsd@GMAIL.COM'),
('Arnoldo', 'Salas', 'Jimenéz','1987-06-18','365763234', 'sdf45I@GMAIL.COM')

INSERT INTO ANIMAL(ID_CLIENTE, ALIAS, ESPECIE, RAZA, COLOR, FECHA_NACIMIENTO)
VALUES
(1,'ROLLY', 'PERRO', 'ROTTWAILER', 'NEGRO', '2018-05-28'),
(2,'MISINGO', 'GATO', 'COMUN', 'RAYAS AMARILLAS', '2013-05-28'),
(7,'BRUNO', 'HAMSTER', 'COMUN', 'CAFE', '2015-05-28'),
(7,'MISCO', 'TORTUGA', 'COMUN', 'CAFE', '2015-05-28'),
(3,'MERLI', 'GATO', 'COMUN', 'CAFE', '2015-05-28'),
(4,'BRACO', 'PERRO', 'COMUN', 'CAFE', '2015-05-28'),
(5,'BANI', 'ARAÑA', 'COMUN', 'CAFE', '2015-05-28'),
(6,'MUSGO', 'PERRO', 'COMUN', 'CAFE', '2015-05-28'),
(5,'FENIX', 'PERRO', 'COMUN', 'CAFE', '2015-05-28')

GO
CREATE OR ALTER TRIGGER ACT_INVENTARIO
ON DETALLE_PRODUCTO AFTER INSERT
AS
DECLARE @id_producto int, @cantidad int
SELECT @cantidad = CANTIDAD FROM inserted
SELECT @id_producto = ID_PRODUCTO FROM inserted
UPDATE PRODUCTO
SET EXISTENCIA = EXISTENCIA - @cantidad
WHERE ID_PRODUCTO = @id_producto
