/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Entidades.*;
import LogicaNegocio.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Date;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Steven
 */
public class CRUDcliente extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */
    DefaultTableModel modelo;

    public CRUDcliente() {
        initComponents();
        setSize(1000, 600);
        setLocationRelativeTo(null);

        try {
            LimpiarTabla();
            cargarDatos("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }

    }

    private void LimpiarTabla() {

        try {
            modelo = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            tblClientes.setModel(modelo);
            modelo.addColumn("ID");
            modelo.addColumn("Nombre");
            modelo.addColumn("Primer apellido");
            modelo.addColumn("Segundo apellido");
            modelo.addColumn("Fecha nacimiento");
            modelo.addColumn("Telefóno");
            modelo.addColumn("Email");
        } catch (Exception ex) {
            throw ex;
        }

    }

    private void cargarDatos(String condicion) throws Exception {
        try {
            LnCliente logica = new LnCliente();
            List<Cliente> lista;
            LimpiarTabla();
            Object[] fila = new Object[7];
            lista = logica.ListarRegistros(condicion);
            for (Cliente cliente : lista) {
                fila[0] = cliente.getId_cliente();
                fila[1] = cliente.getNombre();
                fila[2] = cliente.getApellido1();
                fila[3] = cliente.getApellido2();
                fila[4] = cliente.getFechaNacimiento();
                fila[5] = cliente.getTelefono();
                fila[6] = cliente.getEmail();
                modelo.addRow(fila);
            }
        } catch (Exception ex) {
            throw ex;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnEliminar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veterinaria-Venta");
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setText("Agregar nuevo");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 200, 60));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 170, 60));

        btnSalir.setText("Volver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 130, 60));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 760, 320));

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 130, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        PantallasPrincipal principal = new PantallasPrincipal();
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        AgregarClienteCRUD agCliente = new AgregarClienteCRUD(null, true);
        agCliente.addWindowListener(new WindowAdapter() {
                     
                         @Override
                         public void windowClosed(WindowEvent e){
                             try{
                                 cargarDatos("");
                             }catch(Exception ex){
                                 JOptionPane.showMessageDialog(null, "Error"+ex.getMessage());
                             }
                         }
                     });
        agCliente.setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(tblClientes.getSelectedRow()>-1){
            int fila = tblClientes.getSelectedRow();
            int codigo = (int)tblClientes.getValueAt(fila, 0);
            try{
                LnCliente logica = new LnCliente();
                String condicion = "id_cliente = "+codigo;
                Cliente cliente;
                cliente = logica.ObtenerRegistro(condicion);
                
                if(cliente.isExiste()){
                    modificarClienteCRUD modificar = new modificarClienteCRUD(null, true, cliente);
                     modificar.addWindowListener(new WindowAdapter() {
                     
                         @Override
                         public void windowClosed(WindowEvent e){
                             try{
                                 cargarDatos("");
                             }catch(Exception ex){
                                 JOptionPane.showMessageDialog(null, "Error"+ex.getMessage());
                             }
                         }
                     });
                    modificar.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(this, "No existe el cliente");
                }
                
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage());
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un cliente");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        if(tblClientes.getSelectedRow()>-1){
            
            int resultado;
            int fila = tblClientes.getSelectedRow();
            int codigo = (int)tblClientes.getValueAt(fila, 0);
            try{
                LnCliente logica = new LnCliente();
                String condicion = "id_cliente = "+codigo;
                Cliente cliente;
                cliente = logica.ObtenerRegistro(condicion);
                
                if(cliente.isExiste()){
                    resultado = logica.Eliminar(cliente);
                    if(resultado>0){
                        cargarDatos("");
                        JOptionPane.showMessageDialog(this, "Cliente eliminado");
                        
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "No existe el cliente");
                }
                
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Error: "+ex.getMessage());
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Debe seleccionar un cliente");
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDcliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
